/**
 * Baked word-association table (the "LLM-offline → baked table" backend, §20).
 *
 * Each entry maps a CLUE word to the board words (from the standard set) it is
 * semantically related to. Generated offline (no runtime LLM, no external
 * vectors), so play is deterministic and reproducible and there is no
 * embedding-asset license/size burden. The tableBackend falls back to lexical
 * similarity for any pair not covered here, so custom / out-of-vocabulary word
 * lists still degrade gracefully.
 *
 * To extend coverage (e.g. for a new word list), regenerate this table offline
 * and replace it — keyed by clue word, uppercased. Keys are the spymaster's
 * candidate clue vocabulary; targets should be real board words to be useful.
 */
export const ASSOCIATIONS: Record<string, string[]> = {
    ANIMAL: [
        'BEAR',
        'LION',
        'HORSE',
        'DOG',
        'CAT',
        'WHALE',
        'SHARK',
        'MOUSE',
        'OCTOPUS',
        'PANDA',
        'KANGAROO',
        'RABBIT',
        'BUFFALO',
        'SCORPION',
        'SEAL',
        'DUCK',
        'MOLE',
        'PLATYPUS',
    ],
    BIRD: ['EAGLE', 'HAWK', 'ROBIN', 'DUCK', 'CRANE', 'PENGUIN', 'KIWI', 'PHOENIX'],
    INSECT: ['BUG', 'FLY', 'SPIDER', 'TICK', 'WEB', 'SCORPION', 'WORM', 'SLUG'],
    PET: ['DOG', 'CAT', 'RABBIT', 'MOUSE', 'FISH'],
    WATER: ['BEACH', 'WAVE', 'STREAM', 'POOL', 'ICE', 'SHIP', 'SUB', 'PORT', 'SINK', 'DROP', 'WELL'],
    OCEAN: ['WHALE', 'SHARK', 'SEAL', 'OCTOPUS', 'WAVE', 'SHIP', 'SCUBA DIVER', 'BEACH'],
    SPACE: ['MOON', 'STAR', 'ALIEN', 'JUPITER', 'SATURN', 'MERCURY', 'SATELLITE', 'TELESCOPE'],
    SKY: ['STAR', 'MOON', 'CLOUD', 'PLANE', 'JET', 'WIND'],
    BODY: [
        'ARM',
        'EYE',
        'FACE',
        'FOOT',
        'HAND',
        'HEAD',
        'HEART',
        'THUMB',
        'TOOTH',
        'MOUTH',
        'SHOULDER',
        'SPINE',
        'NAIL',
    ],
    MUSIC: ['BAND', 'NOTE', 'OPERA', 'PIANO', 'CONCERT', 'ORGAN', 'HORN', 'BUGLE', 'FLUTE', 'CONDUCTOR', 'STRING'],
    WINTER: ['ICE', 'SNOW', 'SNOWMAN', 'ANTARCTICA', 'ALPS', 'HIMALAYAS', 'COLD', 'ICE CREAM'],
    MOUNTAIN: ['ALPS', 'HIMALAYAS', 'CLIFF', 'MOUNT', 'VOLCANO', 'PEAK'],
    ROYAL: ['KING', 'QUEEN', 'PRINCESS', 'CROWN', 'KNIGHT', 'RULER'],
    WAR: ['SOLDIER', 'FIGHTER', 'MISSILE', 'BOMB', 'PISTOL', 'FORCE', 'STRIKE', 'SHOT', 'TANK'],
    SPY: ['AGENT', 'SPY', 'NINJA', 'SMUGGLER', 'CODE', 'COVER', 'EMBASSY', 'CONTRACT'],
    MONEY: ['BANK', 'BILL', 'GOLD', 'MINT', 'POUND', 'CASINO', 'MILLIONAIRE', 'CARD', 'STOCK', 'CHANGE'],
    GAMBLE: ['CASINO', 'ROULETTE', 'DICE', 'CARD', 'DECK', 'CLUB', 'LUCK', 'CHIP'],
    SPORT: ['BALL', 'RACKET', 'CRICKET', 'COURT', 'PITCH', 'FIELD', 'BAT', 'STADIUM', 'MATCH'],
    ANCIENT: ['PYRAMID', 'EGYPT', 'AZTEC', 'TEMPLE', 'ATLANTIS', 'DINOSAUR', 'MAMMOTH', 'IVORY'],
    CITY: ['BERLIN', 'ROME', 'LONDON', 'MOSCOW', 'TOKYO', 'BEIJING', 'NEW YORK', 'WASHINGTON', 'CAPITAL'],
    COUNTRY: [
        'AFRICA',
        'AMERICA',
        'AUSTRALIA',
        'CANADA',
        'CHINA',
        'ENGLAND',
        'FRANCE',
        'GERMANY',
        'GREECE',
        'INDIA',
        'MEXICO',
        'TURKEY',
        'EUROPE',
        'CZECH',
    ],
    FOOD: [
        'APPLE',
        'CARROT',
        'CHOCOLATE',
        'HONEY',
        'JAM',
        'KETCHUP',
        'LEMON',
        'OLIVE',
        'ORANGE',
        'PIE',
        'PUMPKIN',
        'HAM',
        'NUT',
        'BERRY',
    ],
    FRUIT: ['APPLE', 'LEMON', 'ORANGE', 'BERRY', 'KIWI', 'OLIVE'],
    KITCHEN: ['PLATE', 'FORK', 'PAN', 'COOK', 'MUG', 'BOTTLE', 'KNIFE', 'STRAW'],
    MYTH: ['DRAGON', 'UNICORN', 'GHOST', 'GIANT', 'DWARF', 'ANGEL', 'WITCH', 'LEPRECHAUN', 'CENTAUR', 'PHOENIX'],
    HERO: ['SUPERHERO', 'ROBOT', 'KNIGHT', 'GIANT', 'NINJA', 'AGENT'],
    SCHOOL: ['TEACHER', 'PUPIL', 'SCHOOL', 'BOARD', 'NOTE', 'PAPER', 'DEGREE'],
    TOOL: ['DRILL', 'HOOK', 'NAIL', 'NEEDLE', 'KNIFE', 'FORK', 'SCALE', 'WASHER', 'PIPE', 'BOLT'],
    LIGHT: ['TORCH', 'LASER', 'RAY', 'FIRE', 'LIGHT', 'STAR', 'MATCH'],
    METAL: ['IRON', 'GOLD', 'COPPER', 'LEAD', 'MARBLE'],
    JEWEL: ['DIAMOND', 'GOLD', 'RING', 'CROWN', 'IVORY'],
    TRANSPORT: [
        'CAR',
        'VAN',
        'TRAIN',
        'PLANE',
        'JET',
        'SHIP',
        'HELICOPTER',
        'LIMOUSINE',
        'AMBULANCE',
        'ENGINE',
        'TUBE',
    ],
    TIME: ['DAY', 'NIGHT', 'TIME', 'WATCH', 'SPRING', 'MARCH', 'DATE'],
    CRIME: ['THIEF', 'SMUGGLER', 'PIRATE', 'POLICE', 'AGENT', 'SPY', 'LAWYER', 'COURT'],
    NATURE: ['FOREST', 'GRASS', 'ROSE', 'MAPLE', 'ROOT', 'PALM', 'GREEN', 'GROUND', 'LOG', 'STICK'],
    HOSPITAL: ['DOCTOR', 'NURSE', 'AMBULANCE', 'HOSPITAL', 'DISEASE', 'VET', 'LAB', 'NEEDLE'],
    FIRE: ['FLAME', 'TORCH', 'BURN', 'MATCH', 'VOLCANO', 'BOMB', 'HOT'],
    GHOSTLY: ['GHOST', 'SHADOW', 'SOUL', 'DEATH', 'WITCH', 'NIGHT'],
    THEATRE: ['OPERA', 'PLAY', 'FILM', 'HOLLYWOOD', 'STAR', 'CAST', 'MODEL'],
    JUNGLE: ['GREEN', 'GRASS', 'FOREST', 'PALM', 'ROOT'],
    PAPER: ['NOTE', 'PAPER', 'CARD', 'MAIL', 'POST', 'NOVEL', 'PRESS', 'FILE'],
    KEY: ['KEY', 'LOCK', 'CODE', 'PASS', 'CHEST', 'SAFE'],
    POWER: ['BATTERY', 'CHARGE', 'CELL', 'ENGINE', 'FORCE', 'BOLT'],
};
