/**
 * Error Codes
 *
 * Centralized error code constants used throughout the application.
 */

// Error codes
export const ERROR_CODES = {
    ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
    ROOM_FULL: 'ROOM_FULL',
    ROOM_ALREADY_EXISTS: 'ROOM_ALREADY_EXISTS',
    GAME_IN_PROGRESS: 'GAME_IN_PROGRESS',
    NOT_HOST: 'NOT_HOST',
    NOT_SPYMASTER: 'NOT_SPYMASTER',
    NOT_CLICKER: 'NOT_CLICKER',
    NOT_YOUR_TURN: 'NOT_YOUR_TURN',
    NO_CLUE: 'NO_CLUE',  // Bug #9 fix: Error when trying to reveal without a clue
    CARD_ALREADY_REVEALED: 'CARD_ALREADY_REVEALED',
    GAME_OVER: 'GAME_OVER',
    INVALID_INPUT: 'INVALID_INPUT',
    RATE_LIMITED: 'RATE_LIMITED',
    SERVER_ERROR: 'SERVER_ERROR',
    WORD_LIST_NOT_FOUND: 'WORD_LIST_NOT_FOUND',
    NOT_AUTHORIZED: 'NOT_AUTHORIZED',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
    SESSION_VALIDATION_RATE_LIMITED: 'SESSION_VALIDATION_RATE_LIMITED',
    RESERVED_NAME: 'RESERVED_NAME',
    CANNOT_SWITCH_TEAM_DURING_TURN: 'CANNOT_SWITCH_TEAM_DURING_TURN',
    CANNOT_CHANGE_ROLE_DURING_TURN: 'CANNOT_CHANGE_ROLE_DURING_TURN',
    SPYMASTER_CANNOT_CHANGE_TEAM: 'SPYMASTER_CANNOT_CHANGE_TEAM',
    PLAYER_NOT_FOUND: 'PLAYER_NOT_FOUND',
    GAME_NOT_STARTED: 'GAME_NOT_STARTED'
} as const;
